export const CRATE_PRODUCT_LIST = "CRATE_PRODUCT_LIST";
export const CURRENT_ORDER = "CURRENT_ORDER";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const DECREASE_CART_ITEM = "DECREASE_CART_ITEM";
export const INCREASE_CART_ITEM = "INCREASE_CART_ITEM";
